name: Build DockerImage
description: Build the Docker image and Push to ECR

inputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_region:
    description: 'AWS Region'
    default: 'ap-south-1'
  service:
    description: 'Array of services'
    required: true
  dockerfile:
    description: 'Dockerfile path'
    required: true
    default: 'Dockerfile'
  version:
    description: 'The version of the artifact'
    required: true
  build_args:
    description: 'Build arguments'
    required: false
    default: ''
  download_artifact:
    description: 'Download artifact'
    required: false
    default: 'true'
  multi_arch:
    description: 'Build multi arch image: linux/amd64,linux/arm64'
    required: false
    default: 'false'
  target_arch:
    description: 'Desired architechture for your docker image'
    default: 'linux/amd64'
    required: false
  context:
    description: 'Docker build context path'
    required: false
    default: '.'
  target:
    description: 'Docker build target stage (for multi-stage builds)'
    required: false
    default: ''
  additional_tags:
    description: 'Additional tags to push (newline-separated)'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Fetch Artifacts
      if : ${{ inputs.download_artifact == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: artifacts-${{github.run_id}}
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Set up QEMU
      if: ${{ inputs.multi_arch == 'true' }}
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker - ${{ inputs.service }}
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.service }}:${{ inputs.version }}
          ${{ inputs.additional_tags != '' && format('{0}/{1}:{2}', steps.login-ecr.outputs.registry, inputs.service, inputs.additional_tags) || '' }}
        build-args: ${{ inputs.build_args }}
        target: ${{ inputs.target }}
        push: true
        cache-from: type=gha, scope=${{ github.workflow }}
        cache-to: type=gha, mode=max, scope=${{ github.workflow }}
        platforms: ${{ inputs.multi_arch == 'true' && 'linux/amd64,linux/arm64' || inputs.target_arch }}
